### ISSUE TITLE
Error executing ./Veil-Pillage.py after installation (ImportError: cannot import name transport)

### ISSUE THREAD

**Issue by carlospolop** [Veil-Framework/Veil-Pillage#14]
I have this error after the installation of Veil-Pillage (Using Kali 2016-2):

Traceback (most recent call last):
  File "./Veil-Pillage.py", line 19, in <module>
    from lib import pillage
  File "/root/Escritorio/GIT/Veil/Veil-Pillage_old/lib/pillage.py", line 101, in <module>
    from lib import command_methods
  File "/root/Escritorio/GIT/Veil/Veil-Pillage_old/lib/command_methods.py", line 25, in <module>
    from lib import smb
  File "/root/Escritorio/GIT/Veil/Veil-Pillage_old/lib/smb.py", line 27, in <module>
    from impacket.dcerpc import transport
ImportError: cannot import name transport

**Comment by NotSoEthical** [comment]
Have same error(
I try to  apt-get remove python-impacket and  install the l;atest version of impacket from github and remove, But not working (

pip freeze | grep impacket    
impacket==0.9.16.dev0

/Veil-Pillage.py 
Traceback (most recent call last):
  File "./Veil-Pillage.py", line 19, in <module>
    from lib import pillage
  File "/opt/Veil/Veil-Pillage/lib/pillage.py", line 101, in <module>
    from lib import command_methods
  File "/opt/Veil/Veil-Pillage/lib/command_methods.py", line 25, in <module>
    from lib import smb
  File "/opt/Veil/Veil-Pillage/lib/smb.py", line 26, in <module>
    from impacket.dcerpc import transport, svcctl, srvsvc
ImportError: cannot import name transport


Also tryed to change version of impacket between 0.9.14 0.9.15 abd 0.9.16.dev0

**Comment by NotSoEthical** [comment]
In Kali Linus installed last version of impacket, and there transport.py are in 
/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/
and in older version of impacket in
/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/
Thats why we have an error!
Solved with:
**pip install impacket==0.9.13**

**Comment by ChrisTruncer** [comment]
Thanks!
